### ISSUE TITLE
[configuration]: setup the project

### ISSUE THREAD

**Issue by SalttySugar** [SalttySugar/Nota#2]
## We will need the following dependencies:

- [C# with latest .NET 6 release](https://docs.microsoft.com/ru-ru/dotnet/core/whats-new/dotnet-6);
- [Entity Framework](https://docs.microsoft.com/en-us/ef/) for data access;
- [Xunit](https://xunit.net/) as testing framework;
- [Moq](https://github.com/moq/moq) as mocking framework.
- [Functional extensions](https://github.com/vkhorikov/CSharpFunctionalExtensions)
- [AutoMapper](https://docs.automapper.org/en/stable/Getting-started.html)

## TODO: 
- [x] Strip warnings from Application;
- [x] Add Count method to ICrudService.

## Requirements: 
- [x] Project must follow Microsoft's style guide as much as possible;
- [x] Project has to be set up as a mono repository because in the future we will add angular to this project with nrwl/nx;
- [x] Project's structure must include all interfaces;
- [x] Project's structure must include models;
- [x] Project's structure must include DTOs;
- [ ] Project's structure must include services whose methods throw "NotImplementedException";
- [x] All dependencies are installed and working.
